### ISSUE TITLE
PlexDVRAPI plugin

### ISSUE THREAD

**Issue by chas901** [OpenViX/PlexDVRAPI#14]
Read me file is not clear. Do I have to donate to get the plugin file?

**Comment by AbuBaniaz** [comment]
The manual says to to install it using plugin download menu. There is no need for you  to be transferring files.

**Comment by AbuBaniaz** [comment]
Use a supported image for your receiver rather than hacked images

**Comment by chas901** [comment]
Yh doing it that way didn't work for me. My 'Green (download plugins)' page was always blank whatever i tried.

Anyway andyblac kindly helped me and said to remove the 'src' from the 'PlexDVRAPI' folder. So i did that and FTP it '/usr/lib/enigma2/python/Plugins/SystemPlugins/PlexDVRAPI/'

It then installed itself and Plex DVR plugin popped up in the plugins.

It also works on my supported custom (hacked) image.

Thanks anyway :+1:

**Comment by andyblac** [comment]
"Read me file is not clear. Do I have to donate to get the plugin file?"

no, plugin is free.
