### ISSUE TITLE
Missing readme how to use

### ISSUE THREAD

**Issue by petrmenzel** [OpenViX/PlexDVRAPI#5]
Hi, I have downloaded this bundle to the Plex´s plugin folder. But I do not understand where to find this in the Plex server?

**Comment by Huevos** [comment]
This is for Plex DVR API. Is that what you are using?

**Comment by petrmenzel** [comment]
I thought that I should install it to the Plex server? I did it and my DVR Plex has started to work. 💃

**Comment by AbuBaniaz** [comment]
OK to close?
