### ISSUE TITLE
Installation issue on openvix

### ISSUE THREAD

**Issue by entourage2111** [OpenViX/PlexDVRAPI#6]
Hi, 

I can't seem to find this plugin on openvix. When I go to system plugins, nothing is there. 

Can you please explain how to install this plugin manually? I can't seem to find an ipk file on the thread to upload....

Thank you

**Comment by AbuBaniaz** [comment]
It is definitely in system plugins. 
![plexdvapi](https://user-images.githubusercontent.com/6644489/28902737-d7b1a0e0-77f8-11e7-8d25-dd41dd0463a8.jpg)

Which image/receiver are you using? Please provide build number instead of saying "latest".

**Comment by AbuBaniaz** [comment]
I'm closing this issue. Please post back if there is still a problem.

Menu > Plugins > Green (Download plugins) > System Plugins > Plexdvrapi (version numbers)
Press OK, confirm the install, restart GUI/Enigma2

If you do not see it, it is probably already installed.
