### ISSUE TITLE
Plugin setup crash 

### ISSUE THREAD

**Issue by RobKillilea** [OpenViX/PlexDVRAPI#7]
Hi

Fresh install of OpenViX 5.0.023 on an Octagon SF4008. Installed the plugin from the repo without issue then selected to configure it. Plugin crashed with the attached log. This is a fully stock flash, nothing else has been added or configured yet

Thanks & BR
- R

[Enigma2_crash_2017-08-04_19-03-25.txt](https://github.com/OpenViX/PlexDVRAPI/files/1202366/Enigma2_crash_2017-08-04_19-03-25.txt)

**Comment by AbuBaniaz** [comment]
Can you try 5.0 024 which has semi-up-to-date version

**Comment by RobKillilea** [comment]
Yes, I noticed immediately after posting that there was a new version (I had downloaded the 023 version while waiting for the box to arrive). I have put that on the box now and reinstalled the plugin. Unfortunately I get exactly the same results, attached below

[Enigma2_crash_2017-08-05_14-18-12.txt](https://github.com/OpenViX/PlexDVRAPI/files/1202384/Enigma2_crash_2017-08-05_14-18-12.txt)

Thanks for your speedy response!

**Comment by Huevos** [comment]
Please check in /etc/enigma2. If there are and files with the prefix "DVB-" please delete these and try again.

**Comment by andyblac** [comment]
you have no DVB channels setup

```<   224.988> [Plex DVR API] BaseURL: http://192.168.1.150:6081
<   224.988> [Plex DVR API] FriendlyName: Octagon SF4008
<   224.988> [Plex DVR API] Source: Cable
<   224.988> [Plex DVR API] TunerCount: 0
<   224.988> [Plex DVR API] Channels: 0
<   224.988> [Plex DVR API] BaseURL: http://192.168.1.150:6082
<   224.988> [Plex DVR API] FriendlyName: Octagon SF4008
<   224.988> [Plex DVR API] Source: Antenna
<   224.988> [Plex DVR API] TunerCount: 1
<   224.988> [Plex DVR API] Channels: 0
<   224.988> [Plex DVR API] BaseURL: http://192.168.1.150:6083
<   224.988> [Plex DVR API] FriendlyName: Octagon SF4008
<   224.988> [Plex DVR API] Source: Satellite
<   224.988> [Plex DVR API] TunerCount: 2
<   224.988> [Plex DVR API] Channels: 0
<   224.988> [Plex DVR API] BaseURL: http://192.168.1.150:6084
<   224.988> [Plex DVR API] FriendlyName: Octagon SF4008
<   224.988> [Plex DVR API] Source: Multi
<   224.988> [Plex DVR API] TunerCount: 3
<   224.988> [Plex DVR API] Channels: 0
```

**Comment by RobKillilea** [comment]
Ahh, I was working on setting it up first and then going to move it into position - should have figured that not having channels would be an issue - Thanks!!
I'll check it after adding channels and close the ticket, much appreciated!
